on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build executable
        run: |
          pip install -r requirements.txt
          pyinstaller --hidden-import=PySide2 -wF linux.py
      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: dist/linux

  build-windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build executable
        run: |
          pip install -r requirements.txt
          ls .venv\bin
          .\.venv\bin\pyinstaller.exe -wF windows.py
      - uses: actions/upload-artifact@v2
        with:
          name: windows.exe
          path: dist/windows.exe
