on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build executable
        run: |
          pip install --upgrade pip
          python3.8 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pyinstaller -wF linux.py
      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: dist/linux

  build-windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build executable
        run: |
          pip install --upgrade pip
          python -m venv .venv
          .venv\bin\activate.bat
          pip install -r requirements.txt
          pyinstaller -wF windows.py
      - uses: actions/upload-artifact@v2
        with:
          name: windows.exe
          path: dist/windows.exe
